%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%                       Bayesian Data Analysis
%                       and Signal Processing
%
%                    A PHY 451/551 and I CSI 451/551
%                             FALL 2011
%
%                     Instructor: Kevin H. Knuth
%
%
% HW 3p
% Introduction to Global Warming Data
%
% The purpose of this homework set is to introduce you to data analysis in
% Matlab.  This importing data into Matlab and performing basic manipulations.
%
% We will perform some *crude* analyses of atmospheric CO2 data.
%
% TURN IN:
% Zip file containing:
%    1. this M-file with your code inserted
%    2. The MAT-files containing the data as instructed below
%    3. A report summarizing your work, illustrating your results (figures) and discussing your answers to the questions posed below.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Problem by: Kevin H. Knuth
% Created on: 8 August 2006
% Modified on: 22 Sept 2011
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Download (or unzip) the Vostok Ice Core Sample Data Set
% Import them into Matlab using the Import Data function in the File Menu
% Restructure the data into two arrays:
% vyear <1x363>   - years BP (before present, which was 2003)
% vco2  <1x363>   - co2 concentration in ppm
% V               - number of measurements
% save the results in a mat-file
%
% These data are provided courtesy of:
% Historical carbon dioxide record from the Vostok ice core
% J.-M. Barnola, D. Raynaud, C. Lorius
% Laboratoire de Glaciologie et de Géophysique de l'Environnement, CNRS,
% BP96, 38402 Saint Martin d'Heres Cedex, France 
% and
% N.I. Barkov
% Arctic and Antarctic Research Institute, Beringa Street 38, 199397, St.
% Petersburg, Russia

%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\WYARAVMS\Desktop\HW3\HW3-DATA\vostok\vostok-icecore-co2.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2014/10/06 22:57:24

%% Initialize variables.
filename = 'C:\Users\WYARAVMS\Desktop\HW3\HW3-DATA\vostok\vostok-icecore-co2.txt';
delimiter = {'\t',','};
startRow = 21;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow-1, 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
vostokicecoreco2 = [dataArray{1:end-1}];
%% Clear temporary variables
%clearvars filename delimiter startRow formatSpec fileID dataArray ans;

%%  Restructure the imported data array to column variable names
YearReference=2003;
vyear = YearReference - dataArray{:, 2}';
vyear = flipud(vyear')';
vco2 = dataArray{:, 4}';
vco2 = flipud(vco2')';
vcounter = size(vco2, 2);
save('vostok.mat','vyear', 'vco2', 'vcounter');

%% Plot the CO2 levels over time
figure;
plot(vyear, vco2);
xlabel('Age of the ice (yr BP)');
ylabel('CO2 concentration (ppmv)');
title('Historical CO2 Record from the Vostok Ice Core ');

%%
% QUESTIONS TO DISCUSS IN YOUR REPORT
% What is the range of variability of the CO2 levels?
% Compute the mean and standard deviation of the CO2 levels?
% Plot a histogram of the CO2 levels?

range = max(vco2) - min(vco2);
meanvco2 = mean(vco2);
stvco2 = std(vco2);
fprintf('The range of variability of the CO2 levels: %f\n', range);
fprintf('The mean and standard deviation of the CO2 levels: %f and %f\n', meanvco2, stvco2);

figure;
hist(vco2);
xlabel('CO2 concentration (ppmv)');
title('Histogram of the CO2 levels ');

%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Download (or unzip) the Mauna Loa Atmopheric Sample Data Set
% Import them into Matlab using the Import Data function in the File Menu
% Restructure the data and save them in these arrays:
% myear  <1x557>   - year
% mmonth <1x557>   - month
% mtime  <1x557>   - time in years
% mco2   <1x557>   - co2 concentration in ppm
% M                - number of measurements
% save the results in a mat-file
% WARNING: THERE ARE MISSING DATA VALUES THAT YOU MUST DEAL WITH.
% Dont interpolate them, just omit them from the data array.
%
% These data are provided courtesy of:
% Atmospheric carbon dioxide record from Mauna Loa
% C.D. Keeling and T.P. Whorf
% Carbon Dioxide Research Group, Scripps Institution of Oceanography,
% University of California, La Jolla, California 92093-0444, U.S.A.


%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\WYARAVMS\Desktop\HW3\HW3-DATA\mauna loa\maunaloa_co2.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2014/10/07 00:02:31

%% Initialize variables.
filename = 'C:\Users\WYARAVMS\Desktop\HW3\HW3-DATA\mauna loa\maunaloa_co2.txt';
startRow = 15;
endRow = 61;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%4f%7f%7f%7f%7f%7f%7f%7f%7f%7f%7f%7f%7f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow-1, 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', '', 'WhiteSpace', '', 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Year = dataArray{:, 1};
Jan = dataArray{:, 2};
Feb = dataArray{:, 3};
March = dataArray{:, 4};
April = dataArray{:, 5};
May = dataArray{:, 6};
June = dataArray{:, 7};
July = dataArray{:, 8};
Aug = dataArray{:, 9};
Sept = dataArray{:, 10};
Oct = dataArray{:, 11};
Nov = dataArray{:, 12};
Dec = dataArray{:, 13};

%% Clear temporary variables
%clearvars filename startRow endRow formatSpec fileID dataArray ans;

%% Create output variable
maunaloaco2 = [dataArray{1:end-1}];

%%

% Restructure the data and save them in these arrays:
% myear  <1x557>   - year
% mmonth <1x557>   - month
% mtime  <1x557>   - time in years
% mco2   <1x557>   - co2 concentration in ppm
% M                - number of measurements
% save the results in a mat-file

%%
maunaloaco2 = [dataArray{1:end-1}];
size(maunaloaco2);

% Number of real measures
[l c] = size(maunaloaco2);
mcounter=0;
for i=1:l,
    for j=2:c,
        if (maunaloaco2(i,j) > 0)
            mcounter=mcounter+1;
        end
    end
end

% Alocate the vectors
myear = zeros(1, mcounter);
mmonth = zeros(1, mcounter);
mtime = zeros(1, mcounter);
mco2 = zeros(1, mcounter);

%%
k=1;
for i=1:l,
    for j=2:c,
        if (maunaloaco2(i,j) > 0)
            myear(k) = maunaloaco2(i,1);
            mmonth(k) = j-1;
            mco2(k) = maunaloaco2(i,j);
            mtime(k) = myear(k) + mmonth(k) / 12;
            k=k+1;
        end
    end
end

save('maunaloa.mat', 'myear', 'mmonth', 'mtime', 'mco2', 'mcounter');

%%
% QUESTIONS TO DISCUSS IN YOUR REPORT
% -Plot the CO2 levels over modern times
% -Can you determine (roughly) the period of the oscillations?
% -What could cause this?

figure;
plot(mtime, mco2);
xlabel('Year');
ylabel('CO2 levels');
title('CO2 levels over modern times');

figure; 
plot(mtime(myear==2003),mco2(myear==2003))
xlabel('Month');
ylabel('CO2 levels');
title('CO2 levels over months - 2003 year');


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Combine the two data sets by concatenating the arrays
% time  <1x920>   - time in years
% co2   <1x920>   - co2 concentration in ppm
% S = V + M       - number of measurements
% Remember that the Vostok data is in years before present, while the Mauna
% Loa data are real dates.

time = [vyear, mtime];
co2 = [vco2, mco2];
scounter = vcounter + mcounter;
 
% Plot the CO2 levels over time

figure;
plot(time, co2);
xlabel('year');
ylabel('CO2 levels');
title('Co2 levels - old and modern dates');


% QUESTIONS TO DISCUSS IN YOUR REPORT
% - What is the CO2 level in May 1986?
% - Given the calculated one standard deviation calculated using the Vostok ice core sample,
%   is it likely that this modern spike is just one of many natural fluctuations?
% - Can you estimate the probability that this modern spike is a natural fluctuation? (extra credit)
% - What is compelling about this analysis?
% - Why is this analysis insufficient?

mv=mean(vco2);
fprintf('Mean of the Vostok data Co2 levels: %f\n', mv);
mc=mean(mco2);
fprintf('Mean of the Mauna Loa dataCo2 levels: %f\n', mc);

mayCo2 = mco2(myear == 1986 & mmonth == 5);
fprintf('CO2 level in May 1986: %f\n', mayCo2);

